### ISSUE TITLE
Project Homepages

### ISSUE THREAD

**Issue by hongxuchen** [Juude/droidReverse#1]
It's better to reference the homepage of these projects in README rather than put the source code/ jars here; or you may consider adding them as git submodules.

Plus, you might have missed [enjarify](https://github.com/google/enjarify).

**Comment by Juude** [comment]
Thank you for your advice.
- enjarify has been added.
- I put some frequently used tools in this repository, So that people can just clone it when they want to de-compile something.other tools will just been added to README.
- git submodule may be used in the future, welcome for pull requests!
